### ISSUE TITLE
import resolution for languages beyond Python, Golang, and Javascript

### ISSUE THREAD

**Issue by ievans** [returntocorp/semgrep#162]
(See docs/matrix.md for our current support status)

**Comment by ievans** [comment]
Related: https://github.com/returntocorp/sgrep/issues/197

**Comment by aryx** [comment]
Actually what do we want for Javascript? 

For python if you do import foo.bar.z as x
then if in your pattern you wrote  foo.bar.z(), then it will match calls like x().

Same for Go if you write import (bar "dir1/dir2/p") 
then if in your pattern you wrote 'p.z()' then it will match also bar.z()' (note here that
this will also match code if someone did import ("different_project/dir2/p") because of the
way Go works where it just use the last element of the dirpath, whether in Python you have
to specificy the full path with the dots (e.g., foo.bar.z).

But for Javascript how it should look like?
And for Java?

**Comment by ievans** [comment]
@aryx this is done, yes?
