### ISSUE TITLE
Warn for the use of $ in a sgrep pattern that is not detected as a metavariable (e.g., $x instead of $X)

### ISSUE THREAD

**Issue by aryx** [returntocorp/semgrep#252]
Right now metavariables have to be in uppercase and contain only letters (e.g., $X, $FOO, but not $FOO_BAR or $X2, or $X).
The rational behind this is that some languages (PHP, Ruby) use already $ for variables (e.g., $global_env) and we may want to be able to match such code. By restricting metavariables to $ with uppercase letters, which are from what i know never used in concrete code, we can match any code and not conflict with existing code.

However, some users may not read the documentation and use $x in their pattern which will silently not match anything. For languages which for sure do not allow $x as an identifier (e.g, Python, Javascript, Java) we should at least warn the user when we parse such pattern code that he may have done a mistake and he should use $X instead of $x.

**Comment by aryx** [comment]
This can be done in main_sgrep.ml when we parse the pattern, and can be implemented using a visitor that visit and try to find any use of Id (x, _) when is_metavar x.

**Comment by aryx** [comment]
This would help a bit issue #211

**Comment by IagoAbal** [comment]
Hi!
  
I want to give this a try, but I have some comments.

My first comment is whether this should be a warning or an error. If a language does not allow something like `$x` as an identifier, then I guess that `$x` is guaranteed to match nothing. If that's the case, couldn't this be an error instead? Warnings are easy to miss.

There seems to be two definitions of meta-variable. One comes from Pfff (`Ast_fuzzy.is_metavar`), this one just requires the identifier to start with a dollar. The second comes from sgrep (`Metavars_generic.is_metavar_name`), this one is stricter as it requires that the dollar is followed by uppercase letters only. If Pfff could use the same definition as sgrep, then one could already report an error during lexing for the relevant languages. This would also allow to distinguish meta-variables explicitly already in `Ast_generic` (e.g. `| Id of ident * bool (* is meta-var? *) * id_info`).

Otherwise, if you prefer checking for this condition using a visitor, I guess you want a visitor like `Visitor_java` but for `Ast_generic`? I did not find any for `Ast_generic` but maybe there is already one? I see that you are generating some of that code with ocamltarzan. I assume that I should first make a pull request to Pfff to add this visitor, and then a separate one to sgrep to use the visitor to implement the check.

What do you think?

**Comment by aryx** [comment]
On Mon, Apr 13, 2020 at 8:35 PM Iago Abal <notifications@github.com> wrote:

> Hi!
>

Hi Iago, thx for doing this.


> I want to give this a try, but I have some comments.
>
> My first comment is whether this should be a warning or an error. If a
> language does not allow something like $x as an identifier, then I guess
> that $x is guaranteed to match nothing. If that's the case, couldn't this
> be an error instead? Warnings are easy to miss.
>
Yes error is probably better.


> There seems to be two definitions of meta-variable. One comes from Pfff (
> Ast_fuzzy.is_metavar), this one just requires the identifier to start
> with a dollar. The second comes from sgrep (
> Metavars_generic.is_metavar_name), this one is stricter as it requires
> that the dollar is followed by uppercase letters only. If Pfff could use
> the same definition as sgrep, then one could already report an error during
> lexing for the relevant languages. This would also allow to distinguish
> meta-variables explicitly already in Ast_generic (e.g. | Id of ident *
> bool (* is meta-var? *) * id_info).
>
The important one is Metavars_generic.is_metavar_name. Recently the code in
sgrep/sgrep/lib/ got split and the fuzzy stuff has been moved out in
sgrep/sgrep/lib_fuzzy as it's not
as important that  the ast_generic part of sgrep.

Yes we could modify Ast_generic Id indeed. I prefer the visitor solution
though for now as I want sgrep-related modifications to Ast_Generic to be
minimum, and I also don't want
to more logic in each lexer.

> Otherwise, if you prefer checking for this condition using a visitor, I
> guess you want a visitor like Visitor_java but for Ast_generic? I did not
> find any for Ast_generic but maybe there is already one? I see that you
> are generating some of that code with ocamltarzan. I assume that I should
> first make a pull request to Pfff to add this visitor, and then a separate
> one to sgrep to use the visitor to implement the check.
>

There is already a visitor for Ast_Generic in pfff/lang_GENERIC/analyze/
visitor_ast.ml


> What do you think?
>
Good questions! I hope I answered most of them. Let me know if you need
more clarifications.
Maybe you can put your code in sgrep/sgrep/lib/check_sgrep.ml or
sgrep/sgrep/lib/lint_sgrep.ml

**Comment by aryx** [comment]
Thx Iago!
